//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.TimeSpan CreationTime { get; set; }
        public string MailFrom { get; set; }
        public string MailTo { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public bool Status { get; set; }
        public bool SendStatus { get; set; }
    }
}
