//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.PatientInsurances = new HashSet<PatientInsurance>();
        }
    
        public int PK_Patients { get; set; }
        public string DF_Patients_FirstName { get; set; }
        public string DF_Patients_MiddleName { get; set; }
        public string DF_Patients_LastName { get; set; }
        public string DF_Patients_Address { get; set; }
        public string DF_Patients_Gender { get; set; }
        public byte DF_Patients_Age { get; set; }
        public string DF_Patients_Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientInsurance> PatientInsurances { get; set; }
    }
}
