//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInsurance
    {
        public int PK_PatientInsurances { get; set; }
        public int FK_PatientInsurances_Patients { get; set; }
        public int FK_PatientInsurances_Users { get; set; }
        public int FK_PatientInsurances_Insurances { get; set; }
        public string DF_PatientInsurances_CreationDate { get; set; }
        public string DF_PatientInsurances_CreationTime { get; set; }
    
        public virtual Insurance Insurance { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
    }
}
