//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public int PK_UserPasswords { get; set; }
        public int FK_UserPasswords_Users { get; set; }
        public string DF_UserPasswords_UserId { get; set; }
        public string DF_UserPasswords_UserPassword { get; set; }
    
        public virtual User User { get; set; }
    }
}
